### ISSUE TITLE
Add "Volunteer" and "Register interest" buttons

### ISSUE THREAD

**Issue by elenalape** [compsoc-edinburgh/htb19-site#2]

**Comment by qaisjp** [comment]
Do you have a link for the volunteer button?

Register interest is http://hacktheburgh.com/register-interest (this one is out of date and will be up to date soon, so do not use this link yet)

**Comment by qaisjp** [comment]
The link should now work

**Comment by elenalape** [comment]
Oh sweet, thanks. No, nothing for volunteering. Will create a form rn.
